// First-launch seed for non-personal reference data only. Workout history,
// body metrics, signals, programs, and progression state always start empty.
import * as C from "./core.js";

// Exported: templates.js builds its additional exercise records with this
// same helper so native and web keep the same shape.
export const ex = (name, category, type, group, o = {}) => ({
  name, category, type, movementGroup: group,
  loadBasis: o.loadBasis || C.inferredLoadBasis(type),
  implementCount: o.implementCount || C.inferredImplementCount(type),
  isUnilateral: !!o.isUnilateral,
  defaultRestSeconds: o.defaultRestSeconds ?? 0,
  notes: o.notes || "",
  isShelved: false,
  shelvedNote: "",
  watchSite: null,
  createdAt: o.createdAt || "2000-01-01T00:00:00.000Z",
});

// Generic exercise definitions only. Watch sites and shelving are user-owned
// health choices and are intentionally not present in source defaults.
const exercises = [
  ex("Deadlift", "Main", "barbell", "hinge"),
  ex("Back Squat", "Main", "barbell", "squat"),
  ex("Front Squat", "Main", "barbell", "squat"),
  ex("Overhead Squat", "Main", "barbell", "squat"),
  ex("Barbell Bench", "Main", "barbell", "press"),
  ex("Overhead Press", "Main", "barbell", "press", { notes: "Strict barbell press" }),
  ex("Push Press", "Main", "barbell", "press"),
  ex("Push Jerk", "Main", "barbell", "press"),
  ex("Split Jerk", "Main", "barbell", "press"),
  ex("Incline DB Press", "Main", "dumbbell", "press"),
  ex("Flat DB Press", "Main", "dumbbell", "press"),
  ex("Seated Upright DB Press", "Main", "dumbbell", "press"),
  ex("Overhead DB Press", "Main", "dumbbell", "press"),
  ex("Snatch", "Main", "barbell", "olympic"),
  ex("Clean & Jerk", "Main", "barbell", "olympic"),
  ex("Clean", "Main", "barbell", "olympic"),
  ex("Power Clean", "Main", "barbell", "olympic"),
  ex("Power Snatch", "Main", "barbell", "olympic"),
  ex("Hang Power Clean", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Hang Power Snatch", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Clean Pull", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Snatch Pull", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Romanian Deadlift", "Accessory", "barbell", "hinge", { defaultRestSeconds: 180 }),
  ex("Snatch-grip Deadlift", "Accessory", "barbell", "hinge", { defaultRestSeconds: 180 }),
  ex("Good Morning", "Accessory", "barbell", "hinge", { defaultRestSeconds: 120 }),
  ex("Turkish Get-up", "Accessory", "kettlebell", "core", { isUnilateral: true }),
  ex("Single-arm DB Row", "Accessory", "dumbbell", "pull", { implementCount: 1, isUnilateral: true }),
  ex("Lat Pulldown", "Accessory", "machine", "pull"),
  ex("Chest-supported Row", "Accessory", "machine", "pull"),
  ex("Ring Row", "Accessory", "bodyweight", "pull", { notes: "Face-pull style" }),
  ex("Band Pull-aparts", "Accessory", "band", "pull", { defaultRestSeconds: 60 }),
  ex("Face Pulls", "Accessory", "machine", "pull"),
  ex("Y-T-W Raises", "Accessory", "dumbbell", "shoulder", { defaultRestSeconds: 60 }),
  ex("Band External Rotation", "Accessory", "band", "shoulder", { isUnilateral: true, defaultRestSeconds: 60 }),
  ex("DB Curls", "Accessory", "dumbbell", "arms"),
  ex("DB Overhead Triceps Extension", "Accessory", "dumbbell", "arms"),
  ex("Walking Lunges", "Accessory", "bodyweight", "squat", { isUnilateral: true }),
  ex("GHD Sit-up", "Accessory", "bodyweight", "core"),
  ex("Plank", "Accessory", "timed", "core", { defaultRestSeconds: 60 }),
  ex("Side Plank", "Accessory", "timed", "core", { isUnilateral: true, defaultRestSeconds: 60 }),
  ex("KB Swing", "Accessory", "kettlebell", "hinge"),
  ex("KB Clean", "Accessory", "kettlebell", "olympic", { isUnilateral: true }),
  ex("Dips", "Accessory", "bodyweight", "press"),
  ex("Trap Bar Deadlift", "Main", "barbell", "hinge"),
  ex("Sumo Deadlift", "Main", "barbell", "hinge"),
  ex("Barbell Hip Thrust", "Main", "barbell", "hinge"),
  ex("Hack Squat", "Main", "machine", "squat"),
  ex("Leg Press", "Main", "machine", "squat"),
  ex("Incline Barbell Bench Press", "Main", "barbell", "press"),
  ex("Close-Grip Bench Press", "Main", "barbell", "press"),
  ex("Machine Chest Press", "Main", "machine", "press"),
  ex("Landmine Press", "Main", "barbell", "press", { isUnilateral: true }),
  ex("Barbell Row", "Main", "barbell", "pull"),
  ex("Pendlay Row", "Main", "barbell", "pull"),
  ex("T-Bar Row", "Main", "machine", "pull"),
  ex("Pull-ups", "Accessory", "bodyweight", "pull", { defaultRestSeconds: 120 }),
  ex("Chin-ups", "Accessory", "bodyweight", "pull", { defaultRestSeconds: 120 }),
  ex("Assisted Pull-up", "Accessory", "machine", "pull", { loadBasis: "assisted" }),
  ex("Seated Cable Row", "Accessory", "machine", "pull"),
  ex("One-arm Cable Row", "Accessory", "machine", "pull", { isUnilateral: true }),
  ex("Bent-over DB Row", "Accessory", "dumbbell", "pull"),
  ex("Incline Bench DB Row", "Accessory", "dumbbell", "pull"),
  ex("Straight-arm Pulldown", "Accessory", "machine", "pull"),
  ex("Rear Delt Fly", "Accessory", "dumbbell", "shoulder"),
  ex("Reverse Pec Deck", "Accessory", "machine", "shoulder"),
  ex("DB Lateral Raise", "Accessory", "dumbbell", "shoulder"),
  ex("Cable Lateral Raise", "Accessory", "machine", "shoulder", { isUnilateral: true }),
  ex("DB Front Raise", "Accessory", "dumbbell", "shoulder"),
  ex("Arnold Press", "Accessory", "dumbbell", "press"),
  ex("DB Floor Press", "Accessory", "dumbbell", "press"),
  ex("Cable Chest Fly", "Accessory", "machine", "press"),
  ex("Pec Deck", "Accessory", "machine", "press"),
  ex("Push-ups", "Accessory", "bodyweight", "press", { defaultRestSeconds: 60 }),
  ex("Incline Push-ups", "Accessory", "bodyweight", "press"),
  ex("Decline Push-ups", "Accessory", "bodyweight", "press"),
  ex("Diamond Push-ups", "Accessory", "bodyweight", "press"),
  ex("Close-Grip Push-ups", "Accessory", "bodyweight", "press"),
  ex("Bulgarian Split Squat", "Accessory", "dumbbell", "squat", { isUnilateral: true }),
  ex("Reverse Lunge", "Accessory", "dumbbell", "squat", { isUnilateral: true }),
  ex("Forward Lunge", "Accessory", "dumbbell", "squat", { isUnilateral: true }),
  ex("Step-up", "Accessory", "dumbbell", "squat", { isUnilateral: true }),
  ex("Goblet Squat", "Accessory", "kettlebell", "squat", { defaultRestSeconds: 60 }),
  ex("Leg Extension", "Accessory", "machine", "squat"),
  ex("Seated Leg Curl", "Accessory", "machine", "hinge"),
  ex("Lying Leg Curl", "Accessory", "machine", "hinge"),
  ex("Nordic Hamstring Curl", "Accessory", "bodyweight", "hinge"),
  ex("DB Romanian Deadlift", "Accessory", "dumbbell", "hinge"),
  ex("Glute Bridge", "Accessory", "bodyweight", "hinge"),
  ex("Cable Pull-through", "Accessory", "machine", "hinge"),
  ex("Back Extension", "Accessory", "bodyweight", "hinge"),
  ex("Standing Calf Raise", "Accessory", "machine", "calves"),
  ex("Seated Calf Raise", "Accessory", "machine", "calves"),
  ex("Barbell Curl", "Accessory", "barbell", "arms"),
  ex("Hammer Curl", "Accessory", "dumbbell", "arms"),
  ex("Incline DB Curl", "Accessory", "dumbbell", "arms"),
  ex("Preacher Curl", "Accessory", "machine", "arms"),
  ex("Cable Curl", "Accessory", "machine", "arms"),
  ex("Triceps Pushdown", "Accessory", "machine", "arms"),
  ex("Skull Crusher", "Accessory", "barbell", "arms"),
  ex("Cable Overhead Triceps Extension", "Accessory", "machine", "arms"),
  ex("Ab Wheel Rollout", "Accessory", "bodyweight", "core"),
  ex("Dead Bug", "Accessory", "bodyweight", "core"),
  ex("Bird Dog", "Accessory", "bodyweight", "core", { isUnilateral: true }),
  ex("Pallof Press", "Accessory", "band", "core"),
  ex("Cable Crunch", "Accessory", "machine", "core"),
  ex("Reverse Crunch", "Accessory", "bodyweight", "core"),
  ex("Hollow Hold", "Accessory", "timed", "core"),
  ex("Hanging Knee Raise", "Accessory", "bodyweight", "core"),
  ex("Sit-ups", "Accessory", "bodyweight", "core", { defaultRestSeconds: 45 }),
  ex("Farmer Carry", "Accessory", "dumbbell", "carry"),
  ex("Suitcase Carry", "Accessory", "dumbbell", "carry", { implementCount: 1, isUnilateral: true }),
  ex("Hang Clean", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Hang Snatch", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Muscle Clean", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Muscle Snatch", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Clean High Pull", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("Snatch High Pull", "Accessory", "barbell", "olympic", { defaultRestSeconds: 180 }),
  ex("KB Press", "Accessory", "kettlebell", "press", { isUnilateral: true }),
  ex("KB Row", "Accessory", "kettlebell", "pull", { isUnilateral: true }),
  ex("Banded Row", "Accessory", "band", "pull"),
  ex("Banded Chest Press", "Accessory", "band", "press"),
  ex("Monster Walk", "Accessory", "band", "squat", { isUnilateral: true }),
  ex("Burpees", "Conditioning", "bodyweight", "conditioning", { defaultRestSeconds: 60 }),
  ex("Mountain Climbers", "Conditioning", "bodyweight", "conditioning", { defaultRestSeconds: 45 }),
  ex("Box Jumps", "Conditioning", "bodyweight", "conditioning", { defaultRestSeconds: 60 }),
  ex("Jump Rope", "Conditioning", "conditioning", "conditioning"),
  ex("Row Erg", "Conditioning", "conditioning", "conditioning"),
  ex("Ski Erg", "Conditioning", "conditioning", "conditioning"),
  ex("Elliptical", "Conditioning", "conditioning", "conditioning"),
  ex("Stair Climber", "Conditioning", "conditioning", "conditioning"),
  ex("Sled Push", "Conditioning", "conditioning", "conditioning"),
  ex("Sled Pull", "Conditioning", "conditioning", "conditioning"),
  ex("Battle Ropes", "Conditioning", "conditioning", "conditioning"),
  ex("Swimming", "Conditioning", "conditioning", "conditioning"),
  ex("Walk", "Conditioning", "conditioning", "conditioning", { notes: "Distance / time / incline" }),
  ex("Run-Walk Intervals", "Conditioning", "conditioning", "conditioning", { notes: "Jog min / walk min × rounds" }),
  ex("Bike", "Conditioning", "conditioning", "conditioning"),
  ex("Ruck", "Conditioning", "conditioning", "conditioning"),
];

const gyms = [{
  name: "Main Gym", isDefault: true, defaultBarId: C.barId(C.BARS.bar45lb),
  collarWeightLb: 0, loadingPolicy: "closest",
  plateToggles: C.ALL_STANDARD.map((plate) => ({ value: plate.value, unit: plate.unit, enabled: true })),
  barcodeImage: null, barcodeLabel: "Membership tag",
}];

export const SEED = {
  exercises,
  gyms,
  tracks: [],
  bodyweight: [],
  milestones: [],
  programs: [],
  sessions: [],
};
