import XCTest
@testable import CadenceCore

/// Epic #155 Stage 2: the deterministic legacy-ID function. These vectors
/// were generated by web/app/js's `stableID` and are pinned identically in
/// web/tests/core.test.mjs — the two implementations must agree on every
/// byte so a v10 backup imported on either client derives the same ids.
final class StableIDTests: XCTestCase {
    func testMatchesTheWebImplementationByteForByte() {
        XCTAssertEqual(StableID.uuid(from: "exercise:Back Squat"), "acb48602-df66-4957-a2d9-c78cae576106")
        XCTAssertEqual(StableID.uuid(from: "exercise:Good Morning"), "f29523a4-cf91-49dd-a5df-accc2223e175")
        XCTAssertEqual(StableID.uuid(from: "exercise:Deadlift"), "19a09757-500a-408f-a70f-18e00beafe8b")
        XCTAssertEqual(StableID.uuid(from: "program:demo"), "4d5cec23-bf96-4e22-ab9f-1d5715078be2")
        XCTAssertEqual(StableID.uuid(from: ""), "711a1863-0c97-4a6e-a99b-61b9d1644c6e")
        XCTAssertEqual(StableID.uuid(from: "exercise:Café Curl"), "51492463-ae3e-4033-a696-8af13b918867")
    }

    func testExerciseLegacyIDIsTheNamespacedDerivation() {
        XCTAssertEqual(StableID.exerciseLegacyID(name: "Back Squat"), StableID.uuid(from: "exercise:Back Squat"))
    }

    func testOutputIsAPortableV4ShapedUUID() {
        let id = StableID.uuid(from: "exercise:Anything At All")
        XCTAssertNotNil(UUID(uuidString: id))
        XCTAssertEqual(id[id.index(id.startIndex, offsetBy: 14)], "4")
        XCTAssertEqual(id[id.index(id.startIndex, offsetBy: 19)], "a")
    }
}
