import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { JSDOM } from 'jsdom';
import { plateGeometry, barbellScene } from '../app/js/barbell-scene.js';
const dom = new JSDOM('<html><body></body></html>', { url:'http://localhost/' });
global.document = dom.window.document;
const C = await import('../app/js/core.js');
const B = await import('../app/js/barbell.js');
const counts = [45, 10, 25, 2.5].map(value => ({ plate:{ value,unit:'lb' }, count:1 }));
const solution = C.enteredPlateSolution(C.BARS.bar45lb, counts, 5);
const before = JSON.stringify(solution);
const closed = barbellScene(solution, 'bumper', false);
const open = barbellScene(solution, 'bumper', true);
assert.deepEqual(open.discs.filter(d=>d.side===1).map(d=>d.plate.value), [45,10,25,2.5]);
assert.deepEqual(open.discs.map(d=>d.radius), closed.discs.map(d=>d.radius));
assert.ok(open.width > closed.width);
for (const d of open.discs) {
  const mirror = open.discs.find(m => m.side === -d.side && m.index === d.index);
  assert.equal(mirror.x, -d.x);
  assert.equal(mirror.radius, d.radius);
  assert.ok(Math.abs(d.x)+d.faceRadius+d.depth < open.width/2);
}
const five = { value:5, unit:'kg' };
assert.equal(plateGeometry(five,'bumper').diameter,450);
assert.equal(plateGeometry(five,'steel').diameter,230);
const mixed = barbellScene(C.enteredPlateSolution(C.BARS.bar20kg,[{plate:five,count:1}]), 'bumper', true,
  { '5-kg': { diameter:230, thickness:20 } });
assert.equal(mixed.discs[0].radius,230*.18);
let calls=0;
const stage = B.barbellStage(B.barbellSVG(solution,'full','bumper'), {onExpand:()=>calls++,containerWidth:390});
stage.querySelector('.barbell-expand').click();
assert.equal(calls,1);
const inspector = B.barbellStage(B.barbellSVG(solution,'full','bumper'), {emphasis:'expanded'});
assert.equal(inspector.querySelector('svg.realistic').dataset.exploded,'true');
assert.equal(inspector.querySelectorAll('.barbell-stack-list li').length,4);
const toggle = inspector.querySelector('.barbell-explode');
toggle.click();
assert.equal(inspector.querySelector('svg.realistic').dataset.exploded,'false');
assert.equal(toggle.getAttribute('aria-pressed'),'false');
toggle.click();
assert.equal(inspector.querySelector('svg.realistic').dataset.exploded,'true');
assert.equal(JSON.stringify(solution), before);
const firstIDs=[...inspector.querySelectorAll('[id]')].map(x=>x.id);
const secondIDs=[...B.barbellSVG(solution,'full').svg.querySelectorAll('[id]')].map(x=>x.id);
assert.ok(!secondIDs.some(id=>firstIDs.includes(id)), 'multiple views never collide in SVG paint-server IDs');
assert.equal(inspector.querySelectorAll('.barbell-lock-collar').length,2);
const worker=readFileSync(new URL('../app/sw.js',import.meta.url),'utf8');
for (const asset of ['js/barbell-scene.js','assets/plate-steel.png','assets/plate-bumper.png']) assert.ok(worker.includes(`"${asset}"`));
console.log('Barbell inspection geometry, identity, controls, and offline assets passed');
