// Offline app shell. Cache-first for same-origin GET; network falls back to
// cache so the app opens with no signal (gym basements).
//
// CACHE includes a build token that the Pages deploy stamps with the commit
// SHA (see .github/workflows/pages.yml). That makes THIS file change on every
// release, which is what causes the browser to install the new worker, refresh
// the cached assets, and drop the old cache — i.e. how updates actually reach
// an installed phone.
// Cache Storage is keyed by ORIGIN, not by scope: every project published under
// this github.io account shares one namespace. So this worker owns exactly the
// `cadence-app-` prefix and never deletes a key outside it. The legacy
// `cadence-<build>` shells from when the app was served at the Pages root belong
// to web/sw.js, which retires them.
const CACHE_PREFIX = "cadence-app-";
const CACHE = `${CACHE_PREFIX}__BUILD__`;
const ownedByThisWorker = (key) => key.startsWith(CACHE_PREFIX);
const ASSETS = [
  "assets/plates/bumper-face-detail.png",
  "assets/plates/steel-face-detail.png",
  "./", "index.html", "styles.css", "manifest.webmanifest",
  "js/app.js", "js/core.js", "js/db.js", "js/seed.js", "js/templates.js", "js/programming-defaults.js", "js/program-file.js", "js/program-equipment.js", "js/anatomy.js", "js/ui.js", "js/charts.js", "js/constants.js", "js/barbell.js", "js/barbell-scene.js", "js/barbell-inspector.js", "js/barbell-gl.js", "js/coaching-adapter.js", "js/workout-clock.js", "js/gym-tag.js", "js/hold-timer.js",
  "js/views/home.js", "js/views/program.js", "js/views/history.js", "js/views/activity.js", "js/views/body.js",
  "js/views/signals.js", "js/views/settings.js", "js/views/session.js", "js/views/plates.js",
  "js/tfh.js", "js/views/tfh.js",
  // plate-sprites:begin (generated by tools/install-plate-sprites.mjs)
  "assets/plates/bar-collar-assembled.png",
  "assets/plates/bar-collar-exploded.png",
  "assets/plates/bar-collar-near-assembled.png",
  "assets/plates/bar-collar-near-exploded.png",
  "assets/plates/bar-shaft-assembled.png",
  "assets/plates/bar-shaft-exploded.png",
  "assets/plates/bar-sleeve-assembled.png",
  "assets/plates/bar-sleeve-exploded.png",
  "assets/plates/bar-sleeve-near-assembled.png",
  "assets/plates/bar-sleeve-near-exploded.png",
  "assets/plates/plate-bumper-450x25-assembled.png",
  "assets/plates/plate-bumper-450x25-exploded.png",
  "assets/plates/plate-bumper-450x35-assembled.png",
  "assets/plates/plate-bumper-450x35-exploded.png",
  "assets/plates/plate-bumper-450x40-assembled.png",
  "assets/plates/plate-bumper-450x40-exploded.png",
  "assets/plates/plate-bumper-450x48-assembled.png",
  "assets/plates/plate-bumper-450x48-exploded.png",
  "assets/plates/plate-bumper-450x52-assembled.png",
  "assets/plates/plate-bumper-450x52-exploded.png",
  "assets/plates/plate-bumper-450x60-assembled.png",
  "assets/plates/plate-bumper-450x60-exploded.png",
  "assets/plates/plate-bumper-450x65-assembled.png",
  "assets/plates/plate-bumper-450x65-exploded.png",
  "assets/plates/plate-bumper-450x70-assembled.png",
  "assets/plates/plate-bumper-450x70-exploded.png",
  "assets/plates/plate-bumper-450x75-assembled.png",
  "assets/plates/plate-bumper-450x75-exploded.png",
  "assets/plates/plate-change-135x12-assembled.png",
  "assets/plates/plate-change-135x12-exploded.png",
  "assets/plates/plate-change-160x16-assembled.png",
  "assets/plates/plate-change-160x16-exploded.png",
  "assets/plates/plate-change-175x18-assembled.png",
  "assets/plates/plate-change-175x18-exploded.png",
  "assets/plates/plate-change-190x19-assembled.png",
  "assets/plates/plate-change-190x19-exploded.png",
  "assets/plates/plate-change-210x19-assembled.png",
  "assets/plates/plate-change-210x19-exploded.png",
  "assets/plates/plate-steel-230x20-assembled.png",
  "assets/plates/plate-steel-230x20-exploded.png",
  "assets/plates/plate-steel-325x20-assembled.png",
  "assets/plates/plate-steel-325x20-exploded.png",
  "assets/plates/plate-steel-325x23-assembled.png",
  "assets/plates/plate-steel-325x23-exploded.png",
  "assets/plates/plate-steel-400x21-assembled.png",
  "assets/plates/plate-steel-400x21-exploded.png",
  "assets/plates/plate-steel-400x25-assembled.png",
  "assets/plates/plate-steel-400x25-exploded.png",
  "assets/plates/plate-steel-450x22-assembled.png",
  "assets/plates/plate-steel-450x22-exploded.png",
  "assets/plates/plate-steel-450x27-assembled.png",
  "assets/plates/plate-steel-450x27-exploded.png",
  "assets/plates/plate-steel-450x30-assembled.png",
  "assets/plates/plate-steel-450x30-exploded.png",
  // plate-sprites:end
  "js/plate-sprites.js",
  "assets/vitruvian-front.jpeg", "assets/vitruvian-back.jpeg",
  "assets/vitruvian-front-traps.svg", "assets/vitruvian-front-delts.svg", "assets/vitruvian-front-chest.svg",
  "assets/vitruvian-front-biceps.svg", "assets/vitruvian-front-forearms.svg", "assets/vitruvian-front-obliques.svg",
  "assets/vitruvian-front-abs.svg", "assets/vitruvian-front-quads.svg", "assets/vitruvian-front-adductors.svg",
  "assets/vitruvian-back-traps.svg", "assets/vitruvian-back-delts.svg", "assets/vitruvian-back-lats.svg",
  "assets/vitruvian-back-triceps.svg", "assets/vitruvian-back-lowerback.svg", "assets/vitruvian-back-forearms.svg",
  "assets/vitruvian-back-glutes.svg", "assets/vitruvian-back-hamstrings.svg", "assets/vitruvian-back-calves.svg",
  "icons/icon-192.png", "icons/icon-512.png", "icons/apple-touch-icon.png",
];

self.addEventListener("install", (e) => {
  // Don't skipWaiting automatically — the new worker waits so the app can offer
  // a "refresh to update" prompt. It still activates on the next cold launch
  // once the old clients are gone.
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys
        .filter((k) => ownedByThisWorker(k) && k !== CACHE)
        .map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// The app posts this when the user taps "Refresh" on the update prompt.
self.addEventListener("message", (e) => {
  if (e.data && e.data.type === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (e) => {
  const req = e.request;
  if (req.method !== "GET" || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      const copy = res.clone();
      caches.open(CACHE).then((c) => c.put(req, copy)).catch(() => {});
      return res;
    }).catch(() => caches.match("index.html")))
  );
});
