// Generated by web/tools/install-plate-sprites.mjs from render-plate-sprites.py output. Do not edit.
export const PLATE_SPRITES = {
 "unit": 81,
 "angles": {
  "assembled": 18,
  "exploded": 38
 },
 "elevation": 13.8865,
 "plates": {
  "bumper:25-kg": "bumper-450x70",
  "bumper:20-kg": "bumper-450x60",
  "bumper:15-kg": "bumper-450x48",
  "bumper:10-kg": "bumper-450x35",
  "bumper:5-kg": "bumper-450x25",
  "bumper:10-lb": "bumper-450x25",
  "bumper:55-lb": "bumper-450x75",
  "bumper:45-lb": "bumper-450x65",
  "bumper:35-lb": "bumper-450x52",
  "bumper:25-lb": "bumper-450x40",
  "steel:25-kg": "steel-450x27",
  "steel:45-lb": "steel-450x27",
  "steel:20-kg": "steel-450x22",
  "steel:15-kg": "steel-400x21",
  "steel:10-kg": "steel-325x20",
  "steel:5-kg": "steel-230x20",
  "steel:10-lb": "steel-230x20",
  "steel:55-lb": "steel-450x30",
  "steel:35-lb": "steel-400x25",
  "steel:25-lb": "steel-325x23",
  "change:2.5-kg": "change-210x19",
  "change:2-kg": "change-190x19",
  "change:5-lb": "change-190x19",
  "change:1.5-kg": "change-175x18",
  "change:1.25-kg": "change-160x16",
  "change:1-kg": "change-160x16",
  "change:2.5-lb": "change-160x16",
  "change:0.5-kg": "change-135x12",
  "change:1.25-lb": "change-135x12"
 },
 "sprites": {
  "bar-collar-assembled": {
   "file": "bar-collar-assembled.png",
   "kind": "collar",
   "angle": "assembled",
   "size": [
    320,
    320
   ],
   "axisStart": [
    119.68,
    163.14
   ],
   "axisEnd": [
    200.19,
    156.87
   ],
   "spanUnits": 14.58
  },
  "bar-collar-exploded": {
   "file": "bar-collar-exploded.png",
   "kind": "collar",
   "angle": "exploded",
   "size": [
    320,
    320
   ],
   "axisStart": [
    126.53,
    166.28
   ],
   "axisEnd": [
    193.24,
    153.77
   ],
   "spanUnits": 14.58
  },
  "bar-collar-near-assembled": {
   "file": "bar-collar-near-assembled.png",
   "kind": "collar-near",
   "angle": "assembled",
   "size": [
    320,
    320
   ],
   "axisStart": [
    119.68,
    163.14
   ],
   "axisEnd": [
    200.19,
    156.87
   ],
   "spanUnits": 14.58
  },
  "bar-collar-near-exploded": {
   "file": "bar-collar-near-exploded.png",
   "kind": "collar-near",
   "angle": "exploded",
   "size": [
    320,
    320
   ],
   "axisStart": [
    126.53,
    166.28
   ],
   "axisEnd": [
    193.24,
    153.77
   ],
   "spanUnits": 14.58
  },
  "bar-shaft-assembled": {
   "file": "bar-shaft-assembled.png",
   "kind": "shaft",
   "angle": "assembled",
   "size": [
    1600,
    320
   ],
   "axisStart": [
    116.24,
    213.32
   ],
   "axisEnd": [
    1458.59,
    108.64
   ],
   "spanUnits": 330
  },
  "bar-shaft-exploded": {
   "file": "bar-shaft-exploded.png",
   "kind": "shaft",
   "angle": "exploded",
   "size": [
    1600,
    320
   ],
   "axisStart": [
    222.51,
    268.28
   ],
   "axisEnd": [
    1335.9,
    59.51
   ],
   "spanUnits": 330
  },
  "bar-sleeve-assembled": {
   "file": "bar-sleeve-assembled.png",
   "kind": "sleeve",
   "angle": "assembled",
   "size": [
    900,
    300
   ],
   "axisStart": [
    65.93,
    179.95
   ],
   "axisEnd": [
    820.96,
    121.07
   ],
   "spanUnits": 150
  },
  "bar-sleeve-exploded": {
   "file": "bar-sleeve-exploded.png",
   "kind": "sleeve",
   "angle": "exploded",
   "size": [
    900,
    300
   ],
   "axisStart": [
    126.09,
    210.74
   ],
   "axisEnd": [
    752.25,
    93.33
   ],
   "spanUnits": 150
  },
  "bar-sleeve-near-assembled": {
   "file": "bar-sleeve-near-assembled.png",
   "kind": "sleeve-near",
   "angle": "assembled",
   "size": [
    900,
    300
   ],
   "axisStart": [
    65.93,
    179.95
   ],
   "axisEnd": [
    820.96,
    121.07
   ],
   "spanUnits": 150
  },
  "bar-sleeve-near-exploded": {
   "file": "bar-sleeve-near-exploded.png",
   "kind": "sleeve-near",
   "angle": "exploded",
   "size": [
    900,
    300
   ],
   "axisStart": [
    126.09,
    210.74
   ],
   "axisEnd": [
    752.25,
    93.33
   ],
   "spanUnits": 150
  },
  "plate-bumper-450x25-assembled": {
   "file": "plate-bumper-450x25-assembled.png",
   "family": "bumper",
   "shape": "450x25",
   "angle": "assembled",
   "faceCenter": [
    244.06,
    256.93
   ],
   "faceRadius": 222.71,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x25-exploded": {
   "file": "plate-bumper-450x25-exploded.png",
   "family": "bumper",
   "shape": "450x25",
   "angle": "exploded",
   "faceCenter": [
    246.1,
    257.86
   ],
   "faceRadius": 222.93,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x35-assembled": {
   "file": "plate-bumper-450x35-assembled.png",
   "family": "bumper",
   "shape": "450x35",
   "angle": "assembled",
   "faceCenter": [
    239.28,
    257.3
   ],
   "faceRadius": 222.8,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x35-exploded": {
   "file": "plate-bumper-450x35-exploded.png",
   "family": "bumper",
   "shape": "450x35",
   "angle": "exploded",
   "faceCenter": [
    242.12,
    258.6
   ],
   "faceRadius": 223.11,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x40-assembled": {
   "file": "plate-bumper-450x40-assembled.png",
   "family": "bumper",
   "shape": "450x40",
   "angle": "assembled",
   "faceCenter": [
    236.88,
    257.49
   ],
   "faceRadius": 222.84,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x40-exploded": {
   "file": "plate-bumper-450x40-exploded.png",
   "family": "bumper",
   "shape": "450x40",
   "angle": "exploded",
   "faceCenter": [
    240.13,
    258.97
   ],
   "faceRadius": 223.2,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x48-assembled": {
   "file": "plate-bumper-450x48-assembled.png",
   "family": "bumper",
   "shape": "450x48",
   "angle": "assembled",
   "faceCenter": [
    233.05,
    257.79
   ],
   "faceRadius": 222.91,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x48-exploded": {
   "file": "plate-bumper-450x48-exploded.png",
   "family": "bumper",
   "shape": "450x48",
   "angle": "exploded",
   "faceCenter": [
    236.95,
    259.57
   ],
   "faceRadius": 223.34,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x52-assembled": {
   "file": "plate-bumper-450x52-assembled.png",
   "family": "bumper",
   "shape": "450x52",
   "angle": "assembled",
   "faceCenter": [
    231.14,
    257.94
   ],
   "faceRadius": 222.95,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x52-exploded": {
   "file": "plate-bumper-450x52-exploded.png",
   "family": "bumper",
   "shape": "450x52",
   "angle": "exploded",
   "faceCenter": [
    235.35,
    259.87
   ],
   "faceRadius": 223.41,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x60-assembled": {
   "file": "plate-bumper-450x60-assembled.png",
   "family": "bumper",
   "shape": "450x60",
   "angle": "assembled",
   "faceCenter": [
    227.3,
    258.24
   ],
   "faceRadius": 223.02,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x60-exploded": {
   "file": "plate-bumper-450x60-exploded.png",
   "family": "bumper",
   "shape": "450x60",
   "angle": "exploded",
   "faceCenter": [
    232.16,
    260.47
   ],
   "faceRadius": 223.55,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x65-assembled": {
   "file": "plate-bumper-450x65-assembled.png",
   "family": "bumper",
   "shape": "450x65",
   "angle": "assembled",
   "faceCenter": [
    224.9,
    258.42
   ],
   "faceRadius": 223.07,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x65-exploded": {
   "file": "plate-bumper-450x65-exploded.png",
   "family": "bumper",
   "shape": "450x65",
   "angle": "exploded",
   "faceCenter": [
    230.16,
    260.84
   ],
   "faceRadius": 223.64,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x70-assembled": {
   "file": "plate-bumper-450x70-assembled.png",
   "family": "bumper",
   "shape": "450x70",
   "angle": "assembled",
   "faceCenter": [
    222.5,
    258.61
   ],
   "faceRadius": 223.11,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x70-exploded": {
   "file": "plate-bumper-450x70-exploded.png",
   "family": "bumper",
   "shape": "450x70",
   "angle": "exploded",
   "faceCenter": [
    228.17,
    261.22
   ],
   "faceRadius": 223.73,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x75-assembled": {
   "file": "plate-bumper-450x75-assembled.png",
   "family": "bumper",
   "shape": "450x75",
   "angle": "assembled",
   "faceCenter": [
    220.1,
    258.8
   ],
   "faceRadius": 223.15,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-bumper-450x75-exploded": {
   "file": "plate-bumper-450x75-exploded.png",
   "family": "bumper",
   "shape": "450x75",
   "angle": "exploded",
   "faceCenter": [
    226.17,
    261.59
   ],
   "faceRadius": 223.82,
   "hubRadius": 0.235,
   "size": [
    512,
    512
   ]
  },
  "plate-change-135x12-assembled": {
   "file": "plate-change-135x12-assembled.png",
   "family": "change",
   "shape": "135x12",
   "angle": "assembled",
   "faceCenter": [
    236.88,
    257.49
   ],
   "faceRadius": 222.84,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-135x12-exploded": {
   "file": "plate-change-135x12-exploded.png",
   "family": "change",
   "shape": "135x12",
   "angle": "exploded",
   "faceCenter": [
    240.13,
    258.97
   ],
   "faceRadius": 223.2,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-160x16-assembled": {
   "file": "plate-change-160x16-assembled.png",
   "family": "change",
   "shape": "160x16",
   "angle": "assembled",
   "faceCenter": [
    234.49,
    257.68
   ],
   "faceRadius": 222.89,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-160x16-exploded": {
   "file": "plate-change-160x16-exploded.png",
   "family": "change",
   "shape": "160x16",
   "angle": "exploded",
   "faceCenter": [
    238.14,
    259.35
   ],
   "faceRadius": 223.28,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-175x18-assembled": {
   "file": "plate-change-175x18-assembled.png",
   "family": "change",
   "shape": "175x18",
   "angle": "assembled",
   "faceCenter": [
    233.87,
    257.73
   ],
   "faceRadius": 222.9,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-175x18-exploded": {
   "file": "plate-change-175x18-exploded.png",
   "family": "change",
   "shape": "175x18",
   "angle": "exploded",
   "faceCenter": [
    237.63,
    259.44
   ],
   "faceRadius": 223.31,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-190x19-assembled": {
   "file": "plate-change-190x19-assembled.png",
   "family": "change",
   "shape": "190x19",
   "angle": "assembled",
   "faceCenter": [
    234.49,
    257.68
   ],
   "faceRadius": 222.89,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-190x19-exploded": {
   "file": "plate-change-190x19-exploded.png",
   "family": "change",
   "shape": "190x19",
   "angle": "exploded",
   "faceCenter": [
    238.14,
    259.35
   ],
   "faceRadius": 223.28,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-210x19-assembled": {
   "file": "plate-change-210x19-assembled.png",
   "family": "change",
   "shape": "210x19",
   "angle": "assembled",
   "faceCenter": [
    236.54,
    257.52
   ],
   "faceRadius": 222.85,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-change-210x19-exploded": {
   "file": "plate-change-210x19-exploded.png",
   "family": "change",
   "shape": "210x19",
   "angle": "exploded",
   "faceCenter": [
    239.85,
    259.03
   ],
   "faceRadius": 223.21,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-230x20-assembled": {
   "file": "plate-steel-230x20-assembled.png",
   "family": "steel",
   "shape": "230x20",
   "angle": "assembled",
   "faceCenter": [
    237.3,
    257.46
   ],
   "faceRadius": 222.84,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-230x20-exploded": {
   "file": "plate-steel-230x20-exploded.png",
   "family": "steel",
   "shape": "230x20",
   "angle": "exploded",
   "faceCenter": [
    240.48,
    258.91
   ],
   "faceRadius": 223.18,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-325x20-assembled": {
   "file": "plate-steel-325x20-assembled.png",
   "family": "steel",
   "shape": "325x20",
   "angle": "assembled",
   "faceCenter": [
    242.77,
    257.03
   ],
   "faceRadius": 222.73,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-325x20-exploded": {
   "file": "plate-steel-325x20-exploded.png",
   "family": "steel",
   "shape": "325x20",
   "angle": "exploded",
   "faceCenter": [
    245.03,
    258.06
   ],
   "faceRadius": 222.98,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-325x23-assembled": {
   "file": "plate-steel-325x23-assembled.png",
   "family": "steel",
   "shape": "325x23",
   "angle": "assembled",
   "faceCenter": [
    240.79,
    257.19
   ],
   "faceRadius": 222.77,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-325x23-exploded": {
   "file": "plate-steel-325x23-exploded.png",
   "family": "steel",
   "shape": "325x23",
   "angle": "exploded",
   "faceCenter": [
    243.38,
    258.37
   ],
   "faceRadius": 223.05,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-400x21-assembled": {
   "file": "plate-steel-400x21-assembled.png",
   "family": "steel",
   "shape": "400x21",
   "angle": "assembled",
   "faceCenter": [
    244.72,
    256.88
   ],
   "faceRadius": 222.7,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-400x21-exploded": {
   "file": "plate-steel-400x21-exploded.png",
   "family": "steel",
   "shape": "400x21",
   "angle": "exploded",
   "faceCenter": [
    246.64,
    257.75
   ],
   "faceRadius": 222.91,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-400x25-assembled": {
   "file": "plate-steel-400x25-assembled.png",
   "family": "steel",
   "shape": "400x25",
   "angle": "assembled",
   "faceCenter": [
    242.57,
    257.05
   ],
   "faceRadius": 222.74,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-400x25-exploded": {
   "file": "plate-steel-400x25-exploded.png",
   "family": "steel",
   "shape": "400x25",
   "angle": "exploded",
   "faceCenter": [
    244.86,
    258.09
   ],
   "faceRadius": 222.99,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x22-assembled": {
   "file": "plate-steel-450x22-assembled.png",
   "family": "steel",
   "shape": "450x22",
   "angle": "assembled",
   "faceCenter": [
    245.49,
    256.82
   ],
   "faceRadius": 222.68,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x22-exploded": {
   "file": "plate-steel-450x22-exploded.png",
   "family": "steel",
   "shape": "450x22",
   "angle": "exploded",
   "faceCenter": [
    247.29,
    257.63
   ],
   "faceRadius": 222.88,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x27-assembled": {
   "file": "plate-steel-450x27-assembled.png",
   "family": "steel",
   "shape": "450x27",
   "angle": "assembled",
   "faceCenter": [
    243.1,
    257.01
   ],
   "faceRadius": 222.73,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x27-exploded": {
   "file": "plate-steel-450x27-exploded.png",
   "family": "steel",
   "shape": "450x27",
   "angle": "exploded",
   "faceCenter": [
    245.3,
    258.01
   ],
   "faceRadius": 222.97,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x30-assembled": {
   "file": "plate-steel-450x30-assembled.png",
   "family": "steel",
   "shape": "450x30",
   "angle": "assembled",
   "faceCenter": [
    241.67,
    257.12
   ],
   "faceRadius": 222.75,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  },
  "plate-steel-450x30-exploded": {
   "file": "plate-steel-450x30-exploded.png",
   "family": "steel",
   "shape": "450x30",
   "angle": "exploded",
   "faceCenter": [
    244.11,
    258.23
   ],
   "faceRadius": 223.02,
   "hubRadius": 0.2,
   "size": [
    512,
    512
   ]
  }
 }
};
